name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.cfg.os }} / ghc ${{ matrix.cfg.ghc }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { os: ubuntu-latest  , ghc: "9.2" }
          - { os: macOS-latest   , ghc: "9.2" }
          - { os: windows-latest , ghc: "9.2" }

    steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - name: "Setup GHC & cabal"
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.cfg.ghc }}
        cabal-version: ${{ matrix.cfg.cabal }}

    - name: "Build executable"
      run: cabal build exe:build-env

    - name: "Command-line: plan, fetch and build lens"
      working-directory: ./tests/test1
      run: |
        cabal run exe:build-env -- plan lens -p plan.json -v2
        cabal run exe:build-env -- fetch -p plan.json -f sources -v2
        cabal run exe:build-env -- build --prefetched -p plan.json -f sources -o install --configure-arg "--ghc-option=-haddock" --no-async -v2
        ghc-pkg --package-db=install/package.conf field lens id

    - name: "Build aeson using a seed file and cabal.config"
      working-directory: ./tests/test2
      run: |
        cabal run exe:build-env -- build --seeds seeds --freeze cabal.config -f sources -o install --no-async -v2
        ghc-pkg --package-db=install/package.conf field aeson id
