name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.cfg.os }} / ghc ${{ matrix.cfg.ghc }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { os: ubuntu-latest  , ghc: "9.2" }
          - { os: macOS-latest   , ghc: "9.2.4" }
          - { os: windows-latest , ghc: "9.2" }

    steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - name: "Setup GHC & cabal"
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.cfg.ghc }}
        cabal-version: ${{ matrix.cfg.cabal }}

    - name: "Build executable"
      run: cabal build exe:build-env

    - name: "Test 1: plan, fetch and build lens (command line)"
      working-directory: ./tests/test1
      run: |
        cabal run exe:build-env -- plan lens -p plan.json -v2
        cabal run exe:build-env -- fetch -p plan.json -f sources -v2
        cabal run exe:build-env -- build --prefetched -p plan.json -f sources -o install --configure-arg "--ghc-option=-haddock" -j8 -v2
        ghc-pkg --package-db=install/package.conf field lens id

    - name: "Test 2: build aeson (seed file & cabal.config)"
      working-directory: ./tests/test2
      run: |
        cabal run exe:build-env -- build --seeds seeds --freeze cabal.config -f sources -o install --haddock -v2
        ghc-pkg --package-db=install/package.conf field aeson id

    - name: "Test 3: build c2hs executable (command line)"
      working-directory: ./tests/test3
      run: |
        cabal run exe:build-env -- build exe:c2hs -f sources -o install -v2

    - name: "Test 4: generate a build script for attoparsec and run it"
      working-directory: ./tests/test4
      if: runner.os != 'Windows'
      run: |
        cabal run exe:build-env -- build attoparsec -f sources -o install --script build_atto.sh -v2
        chmod +x build_atto.sh
        ./build_atto.sh
        ghc-pkg --package-db=install/package.conf field attoparsec id

    - name: "Test 5: bootstrap build-env"
      working-directory: ./tests/test5
      run: |
        cabal run exe:build-env -- build build-env:exe:build-env -f fetch -o install --local build-env=../..

    - name: "Test 6: package with multiple libraries"
      working-directory: ./tests/test6
      run: |
        cabal run exe:build-env -- build pkg2:exe:Test -f fetch -o install --local pkg1=pkg1 --local pkg2=pkg2 -j8
